dist: xenial

language: node_js

node_js: '8.9'

env:
  global:
  - ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

before_script:
  - yarn test

script:
  - yarn dist

cache:
  yarn: true
  directories:
  - node_modules
  - '$HOME/.electron'
  - '$HOME/.cache'

after_success: yarn test:coverage
