version: 0.1.{build}

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\.cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8.9 x64
  - yarn

build_script:
  - yarn dist

test: off
