version: 0.1.{build}

platform:
  - x64

environment:
  ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
  ELECTRON_CACHE: '%USERPROFILE%\cache\electron'
  ELECTRON_BUILDER_CACHE: '%USERPROFILE%\cache\electron-builder'

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\cache'

branches:
  except:
  - gh-pages-src

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10.2 x64
  - yarn install

before_build:
  - yarn keys:decipher
  - yarn build:modules-no-electron
  - yarn test

build_script:
  - if %APPVEYOR_REPO_BRANCH%==stable (yarn build:modules)
  - if %APPVEYOR_REPO_BRANCH%==stable (yarn dist:ci) else (yarn build:prod)

test: off
