version: 0.1.{build}

platform:
  - x64

environment:
  ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
  ELECTRON_CACHE: '%USERPROFILE%\cache\electron'
  ELECTRON_BUILDER_CACHE: '%USERPROFILE%\cache\electron-builder'

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8.9 x64
  - yarn install

before_build:
  - yarn build:modules

build_script:
  - yarn dist:ci

test: off
